# Generated by Django 6.0 on 2025-12-19 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='players', through='games.UserGameProfile', to='games.game'),
        ),
    ]
