# Generated by Django 4.2.27 on 2025-12-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
