# Generated by Django 4.2.27 on 2025-12-22 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobbies', '0002_lobby_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='communication_link',
            field=models.URLField(blank=True, help_text='Link to Discord, TeamSpeak, or in-game party invite.'),
        ),
    ]
