# Generated by Django 6.0 on 2025-12-19 22:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='games/icons/')),
                ('team_size', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='games.game')),
            ],
            options={
                'ordering': ['game', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserGameProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='games.game')),
                ('main_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_user_role', to='games.gamerole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gamerole',
            constraint=models.UniqueConstraint(fields=('game', 'name'), name='unique_game_roles'),
        ),
        migrations.AddConstraint(
            model_name='usergameprofile',
            constraint=models.UniqueConstraint(fields=('user', 'game'), name='unique_user_profiles'),
        ),
    ]
